language: node_js
node_js:
  - "node"
install: true
before_script:
  - yarn install
script:
  - CI=false yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master