language: node_js
node_js:
  - "node"
install: true
script:
  - echo "No test defined"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master