language: node_js
node_js:
  - "node"
notifications:
  email:
    on_success: never
    on_failure: never
install: true
before_script:
  - yarn install
script: |
  sed -i '$s/}/performance: {hints: false},\n}/' node_modules/react-scripts-kotlin/config/webpack.config.prod.js && yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master